[package]
name = "rust-project1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.9.2"
openssl = "0.10.28"
base64 = "0.21.0"